# Generated by Django 3.0.5 on 2021-04-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.IntegerField()),
                ('GameName', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
                ('BuildYear', models.IntegerField()),
                ('Downloads', models.IntegerField()),
                ('ActivePlayers', models.IntegerField()),
                ('Size', models.FloatField()),
                ('Creater', models.CharField(max_length=200)),
                ('Version', models.CharField(max_length=200)),
                ('DevicesAvailable', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('PC', 'PC'), ('PlayStation', 'PlayStation'), ('Xbox', 'Xbox')], default='Android', max_length=100)),
            ],
        ),
    ]
