# Generated by Django 3.0.5 on 2021-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.IntegerField()),
                ('Rank', models.IntegerField()),
                ('Score', models.IntegerField()),
                ('GameID', models.IntegerField()),
                ('Achievements', models.CharField(choices=[('Main', 'Main'), ('InGame', 'InGame'), ('Friendship', 'Friendship')], default='Main', max_length=100)),
                ('SessionNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NewsID', models.CharField(max_length=100)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Likes', models.IntegerField()),
                ('Comments', models.CharField(choices=[('Main', 'Main'), ('InGame', 'InGame'), ('Friendship', 'Friendship')], default='Main', max_length=100)),
                ('Category', models.CharField(choices=[('Main', 'Main'), ('InGame', 'InGame'), ('Friendship', 'Friendship')], default='Main', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.IntegerField()),
                ('PlayerName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('SignupDate', models.DateTimeField()),
                ('LastLogin', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlayerID', models.IntegerField()),
                ('Active', models.BooleanField()),
                ('GamesPlayed', models.CharField(choices=[('Main', 'Main'), ('InGame', 'InGame'), ('Friendship', 'Friendship')], default='Main', max_length=100)),
                ('HourPlayed', models.FloatField()),
                ('Warnings', models.IntegerField()),
                ('Banned', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GameID', models.IntegerField()),
                ('UpdateAvailable', models.BooleanField()),
                ('LastUpdate', models.DateTimeField()),
                ('UpdateSize', models.FloatField()),
                ('UpdatedBy', models.CharField(max_length=100)),
                ('UpdatePending', models.BooleanField()),
            ],
        ),
    ]
